/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ee631fc8e33177fb0cea2f3158a9fba9)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	RESEND_API_KEY: string;
	RESEND_FROM: string;
	RESEND_TO: string;
	TURNSTILE_SECRET: string;
	PUBLIC_TURNSTILE_SITEKEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_API_KEY" | "RESEND_FROM" | "RESEND_TO" | "TURNSTILE_SECRET" | "PUBLIC_TURNSTILE_SITEKEY">> {}
}
